language: minimal
services:
- docker
script:
- sudo bash prepare-tests.sh
- sudo bash run-tests.sh
- sudo bash build-docker.sh
deploy:
  provider: s3
  access_key_id: AKIAWKSOQNTFFN47LVWY
  secret_access_key:
    secure: MOGJq1UC7UnpLaT5HXKidTLAey1GjxkkBXJOxkftQ8h2Qx+wkCUNTXQAqhTu+OpWHj77SqX7oGcZN7YEShTC5Pgpx0DiUvpiJwPK3F7SYDGqPvexbXKUZefNfMfr5Y3Xg0GG5V+DlPUNxoGPgJgq0LJ3C7iPGCILMu5fZxvzv1trLrVE3jOBMU49He4O1iDtMPWituAqnVjGmvw1Z+K3cCMdjP0fVeaayCMdixoSeTon38FZug5ayw2p38jPZ7MjNJtzS0/ZSpifEk519ZY2WSD72DXZoFUbEbUfsyMK66mSoOwyn1HtvMlZ0OPheHSAjH/rgq3dtpGJjPDivtrzt2tyhl8mExeciVFZJeXiCJ4YoQCfo0Jqyn1LyLHlSdIZnKrV8JOggDU5DxnFI8Q//bf/YgZ9/QzRE5nLwxWCIhKj1Brs7efiL42+aph+54wu3gB6z7S2t+VE8DdVVZkJCzdHKEvcBuHA9KAx6UHOoKBbzOHYBdIayA3wGZdb0qkGNSUA9Gp3ddeLWlbwRpdGsx7Z5YF/yHvmQAK2930lhqHpZlfTLkymty2oo96P+7VD7r3bZ6jKhh07ZBRbV/ceE2BEh2VYt0hNX4zMKS7H5XLuV5u7nP3TFyy1LL3sSPjez5Xkvl3UtiB90rdJMTDyVxwFY7AT+4f4NFbciIDrvQQ=
  bucket: aws-website-stage-rpfg4
  upload-dir: stats
  local_dir: dist
  skip_cleanup: true
  region: us-east-1
  on:
    branch: master
